2021-03-16 11:14:18 remote_connection.py [line:117] INFO>Could not connect to port 12355 on host 192.168.31.136
2021-03-16 11:14:18 remote_connection.py [line:136] INFO>Could not get IP address for host: 192.168.31.136
2021-03-16 11:14:20 connectionpool.py [line:745] WARNING>Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024E74EE6CC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /wd/hub/session
2021-03-16 11:14:22 connectionpool.py [line:745] WARNING>Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024E74EE6E80>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /wd/hub/session
2021-03-16 11:14:24 connectionpool.py [line:745] WARNING>Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024E74EE6FD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /wd/hub/session
2021-03-16 11:14:27 remote_connection.py [line:117] INFO>Could not connect to port 12355 on host 192.168.31.136
2021-03-16 11:14:27 remote_connection.py [line:136] INFO>Could not get IP address for host: 192.168.31.136
2021-03-16 11:14:29 connectionpool.py [line:745] WARNING>Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024E753A67B8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /wd/hub/session
2021-03-16 11:14:31 connectionpool.py [line:745] WARNING>Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024E753A6A58>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /wd/hub/session
2021-03-16 11:14:34 connectionpool.py [line:745] WARNING>Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024E753A69B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /wd/hub/session
